### ISSUE TITLE
Handle included files in .gitlab-ci.yml

### ISSUE THREAD

**Issue by Ezveus** [moduloTech/modulorails#31]
If the rubocop rule is included in .gitlab-ci.yml through an included file, it should not be appended to the main file.

```yml
include:
  - local: .gitlab/ci/public.yaml
    rules:
      - if: $CI_SERVER_HOST == "gitlab.com"
  - local: .gitlab/ci/private.yaml
    rules:
      - if: $CI_SERVER_HOST == "privategitlab.com"
```
